function invalid_copula_vals(exp_path, family, theta, n, k)

    disc_cop = CopulaCAParametric(family, theta, n, 'theta');

    pdf_approx = disc_cop.getApproxPDFMatrix(k);
    pdf_invalid = disc_cop.getInvalidPDFValues(k);
    pdf_approx_corrected = disc_cop.getApproxPDFMatrix(k, true);
    pdf_true = disc_cop.getPDFMatrix();

    text_file_path = fullfile(exp_path, sprintf('invalid_values_%s_theta_%.1f_n_%i_approx_order_%i.txt', ...
        family, theta, n, k));

    writelines(sprintf('Frobenius norm(approx - approx_corrected) = %.4f', ...
        norm(pdf_approx_corrected - pdf_approx, 'fro')), text_file_path)
    writelines(sprintf('Frobenius norm(approx - approx_corrected) / || true ||_F = %.4f', ...
        norm(pdf_approx_corrected - pdf_approx, 'fro') / norm(pdf_true, 'fro')), text_file_path, WriteMode="append")
    writelines(sprintf('Frobenius norm(approx - true) = %.4f', ...
        norm(pdf_true - pdf_approx, 'fro')), text_file_path, WriteMode="append")
    writelines(sprintf('Frobenius norm(approx - true) / || true ||_F = %.4f', ...
        norm(pdf_true - pdf_approx, 'fro') / norm(pdf_true, 'fro')), text_file_path, WriteMode="append")
    writelines(sprintf('Frobenius norm(true - approx_corrected) = %.4f', ...
        norm(pdf_approx_corrected - pdf_true, 'fro')), ...
        text_file_path, WriteMode="append")
    writelines(sprintf('Frobenius norm(true - approx_corrected) / || true ||_F = %.4f', ...
        norm(pdf_approx_corrected - pdf_true, 'fro') / norm(pdf_true, 'fro')), ...
        text_file_path, WriteMode="append")

    save(fullfile(exp_path, sprintf('%s_theta_%.1f_n_%i_approx_order_%i.mat', ...
        family, theta, n, k)), 'pdf_approx_corrected', ...
        'pdf_true', 'pdf_approx', 'pdf_invalid', 'theta', 'n', 'k', 'family')

end